services:
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka-wikipedia
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LOG_DIRS: '/var/lib/kafka/data'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
    volumes:
      - kafka_data:/var/lib/kafka/data

  kafka-init:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka-init
    depends_on:
      - kafka
    entrypoint: [ "/bin/sh", "-c" ]
    command: >
      "
      echo 'Waiting for Kafka to be ready...'
      cub kafka-ready -b kafka:29092 1 30 &&
      kafka-topics --create --if-not-exists --bootstrap-server kafka:29092 --replication-factor 1 --partitions 1 --topic wikipedia-raw &&
      kafka-topics --create --if-not-exists --bootstrap-server kafka:29092 --replication-factor 1 --partitions 1 --topic predictions-stream &&
      echo 'Topics created successfully.'
      "

  # consumer:
  #   build:
  #     context: ./src
  #     dockerfile: Dockerfile
  #   container_name: wikipedia-consumer
  #   command: python consumer_offline_batch.py
  #   restart: on-failure
  #   environment:
  #     KAFKA_SERVER: "kafka:29092"
  #     OUTPUT_DIR: "/data"
  #     OUTPUT_FORMAT: "csv"
  #   volumes:
  #     - ./data:/data
  #   depends_on:
  #     kafka-init:
  #       condition: service_completed_successfully

  producer:
    build:
      context: ./src
      dockerfile: Dockerfile
    container_name: wikipedia-producer
    restart: on-failure
    environment:
      KAFKA_SERVER: "kafka:29092"
    depends_on:
      # consumer:
      #   condition: service_started
      kafka-init:
        condition: service_completed_successfully
  live-consumer:
    build:
      context: ./src
      dockerfile: Dockerfile
    container_name: live-scoring-consumer
    restart: on-failure
    command: python -u live_scoring_consumer.py
    environment:
      KAFKA_SERVER: "kafka:29092"
      INPUT_TOPIC: "wikipedia-raw"
      OUTPUT_TOPIC: "predictions-stream"
      MODEL_PATH: "/models/xgb_bot_detector.json"
    volumes:
      - ./models:/models
    depends_on:
      kafka-init:
        condition: service_completed_successfully
  dashboard:
    build:
      context: ./src
      dockerfile: Dockerfile
    container_name: streamlit-dashboard
    restart: on-failure
    command: streamlit run dashboard.py --server.address=0.0.0.0 --server.port=8501
    ports:
      - "8501:8501"
    environment:
      KAFKA_SERVER: "kafka:29092"
      PREDICTIONS_TOPIC: "predictions-stream"
    depends_on:
      kafka-init:
        condition: service_completed_successfully

  kafdrop:
    image: obsidiandynamics/kafdrop:4.0.1
    container_name: kafdrop-ui
    restart: always
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:29092"
    depends_on:
      - kafka

volumes:
  kafka_data:
